Conduit: Fix PHP 8.1 "substr/trim(null)" exceptions in differential.createrawdiff
Summary:
Bail out earlier when we have a raw diff which is empty (null) in order to avoid some PHP 8.x issues.

Passing null to substr() and trim() is deprecated since PHP 8.1.

```
ERROR 8192: substr(): Passing null to parameter #1 ($string) of type string is deprecated at [/var/www/html/phorge/arcanist/src/parser/ArcanistDiffParser.php:194]
ERROR 8192: trim(): Passing null to parameter #1 ($string) of type string is deprecated at [/var/www/html/phorge/arcanist/src/parser/ArcanistDiffParser.php:198]
```

Closes T16429

Test Plan:
* PHP 8.1
* Go to http://phorge.localhost/conduit/method/differential.createrawdiff/ and press "Call Method"

```
ERROR 8192: substr(): Passing null to parameter #1 ($string) of type string is deprecated at [/var/www/html/phorge/arcanist/src/parser/ArcanistDiffParser.php:194]
arcanist(head=master, ref.master=a50c78c6f93a), phorge(head=master, ref.master=eabb7109df4b)
  #0 substr(NULL, integer, integer) called at [<arcanist>/src/parser/ArcanistDiffParser.php:194]
  #1 ArcanistDiffParser::parseDiff(NULL) called at [<phorge>/src/applications/differential/conduit/DifferentialCreateRawDiffConduitAPIMethod.php:43]
  #2 DifferentialCreateRawDiffConduitAPIMethod::execute(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/method/ConduitAPIMethod.php:180]
  #3 ConduitAPIMethod::executeMethod(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/call/ConduitCall.php:131]
  #4 ConduitCall::executeMethod() called at [<phorge>/src/applications/conduit/call/ConduitCall.php:81]
  #5 ConduitCall::execute() called at [<phorge>/src/applications/conduit/controller/PhabricatorConduitAPIController.php:92]
  #6 PhabricatorConduitAPIController::handleRequest(AphrontRequest) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:284]
  #7 AphrontApplicationConfiguration::processRequest(AphrontRequest, PhutilDeferredLog, AphrontPHPHTTPSink, MultimeterControl) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:203]
  #8 AphrontApplicationConfiguration::runHTTPRequest(AphrontPHPHTTPSink) called at [<phorge>/webroot/index.php:35]

ERROR 8192: trim(): Passing null to parameter #1 ($string) of type string is deprecated at [/var/www/html/phorge/arcanist/src/parser/ArcanistDiffParser.php:198]
arcanist(head=master, ref.master=a50c78c6f93a), phorge(head=master, ref.master=eabb7109df4b)
  #0 trim(NULL) called at [<arcanist>/src/parser/ArcanistDiffParser.php:198]
  #1 ArcanistDiffParser::parseDiff(NULL) called at [<phorge>/src/applications/differential/conduit/DifferentialCreateRawDiffConduitAPIMethod.php:43]
  #2 DifferentialCreateRawDiffConduitAPIMethod::execute(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/method/ConduitAPIMethod.php:180]
  #3 ConduitAPIMethod::executeMethod(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/call/ConduitCall.php:131]
  #4 ConduitCall::executeMethod() called at [<phorge>/src/applications/conduit/call/ConduitCall.php:81]
  #5 ConduitCall::execute() called at [<phorge>/src/applications/conduit/controller/PhabricatorConduitAPIController.php:92]
  #6 PhabricatorConduitAPIController::handleRequest(AphrontRequest) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:284]
  #7 AphrontApplicationConfiguration::processRequest(AphrontRequest, PhutilDeferredLog, AphrontPHPHTTPSink, MultimeterControl) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:203]
  #8 AphrontApplicationConfiguration::runHTTPRequest(AphrontPHPHTTPSink) called at [<phorge>/webroot/index.php:35]

EXCEPTION: (Exception) Can't parse an empty diff! at [<arcanist>/src/parser/ArcanistDiffParser.php:199]
arcanist(head=master, ref.master=a50c78c6f93a), phorge(head=master, ref.master=eabb7109df4b)
  #0 <#2> ArcanistDiffParser::parseDiff(NULL) called at [<phorge>/src/applications/differential/conduit/DifferentialCreateRawDiffConduitAPIMethod.php:43]
  #1 <#2> DifferentialCreateRawDiffConduitAPIMethod::execute(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/method/ConduitAPIMethod.php:180]
  #2 <#2> ConduitAPIMethod::executeMethod(ConduitAPIRequest) called at [<phorge>/src/applications/conduit/call/ConduitCall.php:131]
  #3 <#2> ConduitCall::executeMethod() called at [<phorge>/src/applications/conduit/call/ConduitCall.php:81]
  #4 <#2> ConduitCall::execute() called at [<phorge>/src/applications/conduit/controller/PhabricatorConduitAPIController.php:92]
  #5 phlog(Exception) called at [<phorge>/src/applications/conduit/controller/PhabricatorConduitAPIController.php:120]
  #6 PhabricatorConduitAPIController::handleRequest(AphrontRequest) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:284]
  #7 AphrontApplicationConfiguration::processRequest(AphrontRequest, PhutilDeferredLog, AphrontPHPHTTPSink, MultimeterControl) called at [<phorge>/src/aphront/configuration/AphrontApplicationConfiguration.php:203]
  #8 AphrontApplicationConfiguration::runHTTPRequest(AphrontPHPHTTPSink) called at [<phorge>/webroot/index.php:35]
```

Reviewers: O1 Blessed Committers, mainframe98

Reviewed By: O1 Blessed Committers, mainframe98

Subscribers: mainframe98, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16429

Differential Revision: https://we.phorge.it/D26640