Cast an int to string before passing it to addcslashes()
Summary:
Get a little bit closer to rendering the Phorge frontpage with PHP strict typing enabled.
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict

Per https://www.php.net/manual/en/function.addcslashes.php, it expects a string as the first parameter, so cast.

```
EXCEPTION: (TypeError) addcslashes(): Argument #1 ($string) must be of type string, int given at [<arcanist>/src/utils/utils.php:1973]
  #0 <#2> addcslashes(integer, string) called at [<arcanist>/src/utils/utils.php:1973]
  #1 <#2> phutil_encode_log(integer) called at [<arcanist>/src/filesystem/PhutilDeferredLog.php:234]
```

Refs T16725

Test Plan: Insert `declare( strict_types = 1 );` into all Arcanist PHP files; apply D27125 in Phorge; invert the `if ($console)` condition in Phorge's `PhabricatorStandardPageView::willSendResponse()`; in combination with D27127 succeed in getting the Phorge frontpage rendered which has no dashboard panels etc configured.

Reviewers: O1 Blessed Committers, avivey

Reviewed By: O1 Blessed Committers, avivey

Subscribers: avivey, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16725

Differential Revision: https://we.phorge.it/D27126