PhutilTranslator: Cast PhutilNumber's number to float
Summary:
In several places we set a PhutilNumber as an %s parameter within a pht() string.
This trickles down to `PhutilNumber::formatNumber()` which expects a float as its first parameter instead of a string.
As we know for sure in `PhuilTranslator::translate()` that we have a PhutilNumber (due to the existing instanceof check), cast the string to a float here.

```
EXCEPTION: (TypeError) number_format(): Argument #1 ($num) must be of type int|float, string given at [<arcanist>/src/internationalization/PhutilTranslator.php:256]
  #0 <#2> number_format(string, integer, string, string) called at [<arcanist>/src/internationalization/PhutilTranslator.php:256]
  #1 <#2> PhutilTranslator::formatNumber(string, integer) called at [<arcanist>/src/internationalization/PhutilTranslator.php:120]
  #2 <#2> PhutilTranslator::translate(string, PhutilNumber) called at [<arcanist>/src/internationalization/pht.php:16]

  #3 <#2> pht(string, PhutilNumber) called at [<phorge>/src/applications/multimeter/storage/MultimeterEvent.php:54]
  #3 <#2> pht(string, PhutilNumber) called at [<phorge>/src/applications/ponder/query/PonderQuestionSearchEngine.php:171]
  #3 <#2> pht(string, PhutilNumber) called at [<phorge>/src/applications/xhprof/query/PhabricatorXHProfSampleSearchEngine.php:78]
```

Refs T16725

Test Plan:
* Apply D27125 in Phorge
* Insert `declare( strict_types = 1 );` into all Arcanist and Phorge PHP files
* Go to http://phorge.localhost/multimeter/
* Go to http://phorge.localhost/ponder/
* Go to http://phorge.localhost/xhprof/
* After applying this patch, see that all three pages render now

Reviewers: O1 Blessed Committers, avivey

Reviewed By: O1 Blessed Committers, avivey

Subscribers: avivey, tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16725

Differential Revision: https://we.phorge.it/D27156