Cast TempFile to string for file path in Filesystem::writeFile()
Summary:
Get a bit closer to rendering Phorge pages with PHP strict typing enabled.
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict

`Filesystem::writeFile()` is pretty much a wrapper for PHP's `file_put_contents()` which expects a string for the file path.
`Filesystem::writeFile()` is called in many places, thus do not fix the caller but cast in the method itself.

```
EXCEPTION: (TypeError) strncmp(): Argument #1 ($string1) must be of type string, TempFile given at [<arcanist>/src/filesystem/Filesystem.php:861]
  #0 <#2> strncmp(TempFile, string, integer) called at [<arcanist>/src/filesystem/Filesystem.php:861]
  #1 <#2> Filesystem::isPharPath(TempFile) called at [<arcanist>/src/filesystem/Filesystem.php:998]
  #2 <#2> Filesystem::resolvePath(TempFile) called at [<arcanist>/src/filesystem/Filesystem.php:58]
  #3 <#2> Filesystem::assertWritableFile(TempFile) called at [<arcanist>/src/filesystem/Filesystem.php:91]
  #4 <#2> Filesystem::writeFile(TempFile, string) called at [<arcanist>/src/filesystem/TempFile.php:55]
  #5 <#2> TempFile::__construct() called at [<phorge>/src/applications/config/check/PhabricatorBinariesSetupCheck.php:36]
```

Refs T16725

Test Plan:
* Insert `declare( strict_types = 1 );` into all Arcanist and Phorge PHP files
* Invert the `if ($console)` check in `PhabricatorStandardPageView::willSendResponse()`
* Go to the Setup Issues page at http://phorge.localhost/config/issue/
* See that it renders after applying this patch

Reviewers: O1 Blessed Committers, valerio.bozzolan

Reviewed By: O1 Blessed Committers, valerio.bozzolan

Subscribers: tobiaswiese, valerio.bozzolan, Matthew, Cigaryno

Maniphest Tasks: T16725

Differential Revision: https://we.phorge.it/D27192